fe-8 implement post comment to an article
rangararazin/zin-fe-ncnews pull request #6
Opened 2022-12-07 09:46 UTC by rangararazin

2022-12-07 10:02 UTC, callumu21 requested changes
Good start, Razin! I've left a few comments that need to be addressed before this can be approved. Once you've made the changes, please resubmit this PR 😄

2022-12-07 10:02 UTC, callumu21 commented on src/component/CommentAdder.jsx
> +    postComments(article_id, currentUser, newComment).then(( commentRes ) => {
You need a way of preventing users from pressing submit multiple times before this has completed. On a slow connection, it's currently possible to make multiple posts before the comment is reset and the initial post request is completed.

2022-12-07 10:02 UTC, callumu21 commented on src/utils/api.js
> +  console.log(article_id, user, body);
This can be removed now.

2022-12-07 10:03 UTC, rangararazin commented on src/component/CommentAdder.jsx
> +    alert("Your comment has been added !! ")
Thanks Callum.Will do the changes and resubmit PR.

2022-12-08 09:57 UTC, cjplatten commented
This is working ok now, please be careful when commiting changes to a branch as a lot of changes have been commited here that are not relevant to addressing the previous comments.

2022-12-08 09:59 UTC, merged